---
title: "Guidelines to argue for the inclusion of doctoral work as previous work experience"
author: "translated by Thejasvi Beleyur"
date: "12/2/2021"
output: pdf_document
---

Disclaimer + background: *Please note, this is an unofficial translation of the document titled '*Argumentationsleitfaden zur Anrechnung der Promotion als Berufserfahrung*' released by the Vertretung der Promovierenden der Begabtenförderungswerke. The document is can be found at this [link](http://www.tom-s.org/pi/wp-content/uploads/2019/06/2019-03-30_Leitfaden-zur-Anerkennung-der-Promotion-als-Berufserfahrung.pdf) (click on the word). I am not a native German speaker, please treat this as a rough translation, and/or consult a native speaker for safety! In many places, the translation may seem to be more of a transliteration, and I apologise in advance for this. This is my best attempt at translating this legally-heavy text, and I may be breaking multiple translation/legal conventions unintentionally.*

The following guideline deals with the issue of getting doctoral work reognised as work-experience in public and private sector based employment. For private-sector employment, the skills developed during the doctorate are important for the job itself and this guideline outlines the potential skills to highlight. In addition, the legal basis and conditions to get doctoral stipend considered as relevant work experiene are discussed. In job positions regulated by the collective agreement of the states (TV-L), there are definitions in place of what periods of work are considered work experience. This guideline is split into four sections 1) uniqueness of non-university positions 2) Legal framework and collective agreements in the public services 3) Case-histories and 4) Concluding information and further steps. 


# 1. Employment with/without collecitve agreements outside of academia
The skillsets developed during PhD work are the basis to negotiate pay-grades when taking up a job position with a collective agreement type contract. This is especially important in situations where the work was done in a non-contractual/non-collective agreement type form, without 'standard' pay-grade categories. This includes:

* Professional familiarity with relevant hard/software as well as discipline-specific technologies and equipment 
* Fluency in foreign languages, supported by publications in international journals, conference presentations or work in international teams/collaborations. 
* Rhetorical and presentational skills, or even didactic competencies (teaching experience?)
* Communication and negotiation skills, team-work, networking skills, leadership and guiding experience as shown by training interns or students. 
* Ability to work independently, self-discipline and goal-oriented work 
* Enthusiasm, motivation and perserverance in the face of difficulty and frustration
* Analytical, problem-solving and judgment skills

These competencies and their development is of course dependent on the personality of the candidate and the nature of the PhD work. This is not an exhaustive list, and it is important to think of (highlight) one's own competencies during job application. 

# 2.  Employment with/without collecitve agreements in the public services
Employment in public-service jobs (Öffentlichen Dienst) are governed by the  Collective Agreement of the States (TV-L). The TVL contracts assign 'wage-levels' (Entgeltgruppen, or just 'E') , which are then split into sub-levels based on experience (Erfahrungsstufe/Stufe). Within one wage-level, the salary increases with an increase in the respective experience level. The experience-level is assigned according to a predefined criteria based on the amount of time spent in the job. PhD scholars, interns and scientific employees at universities are typically employed with a TV-L contract, and their contract-based Stufe increases with time spent in the job. At the end of the PhD, contract-based employees thus benefit from the visibly higher Stufe reflected in their contracts, and can expect a higher Stufe assignment in any following job. PhD candidates with stipends however do not experience these benefits as a result of not having a contract. It is thus important to be familiar with the legal guidelines in place.

Firstly, there is no uniformity or relevant precedent case where stipends are recognised as work-experience for the E 13-15  groups. However, there is always the possibility for exceptions to be made with the administration at hand. It is important to note that different stipends may be treated differently here. Therefore, any additional employment along with the stipend has a higher chance of increasing the Erfahrungsstufe assigned. Insititution-agnostic (not bound to any institution) stipends financed by the Bundesministerium für Bildung und Forschung (BMBF) are often not recognised as work-experience. This is in contrast to institutionally based stipends or stipends given out by non-university research institutions, where the stipend may be recognised as work-experience. The following portion will describe the process of work-experience assignment (Einstufung), and the cases of stipend-holders with/out previous work experience and with BMBF and non-BMBF stipends will be discussed. 

### General information for the recognition of stipends
There are two legal possibilities to increase the assigned Erfahrungsstufe in accordance to the appropriate work-experience according to the TVL. The work experience may be considered as 'relevant work-experience' (einschlägige Berufserfahrung) per §16  Abs.2  Satz 1-3  TV-L. Another option is to classify the work experience under §16  Abs.2  Satz4  TV-L, which covers the staffing requirements ('Deckung des Personalbedarfs'), where the previous experience is seen as necessary for the current job. 

Attention: When the contract has already been signed (without consideration of previous work experience), it is not be possible to revise the Erfahrungsstufe retroactively. Moreover, the work-experience that is to be considered cannot be more than 6 months, or for scientific positions, 12 months in the past. 

### a. Relevant work-experience (Einschlägige Berufserfahrung) (§16Abs.2 S.1-3TV-L)
The criteria for experience-level assigment is set in §16 Abs.2 of the TV-L: *'At the time of employment, the employee will be assigned Stufe 1, in the absence of any relevant work experience'*. The decisive factor here is whether work done under a stipend can be considered relevant work experience. According to the protocol statement 1 on §16 Abs.2 TV-L, relevant experience is *'a work experience that is transferrable or directly relevant to the duties of the job'^[please get this and all following protocol statements especially verified by a native speaker, or someone familiar with German legalese.]*. In principle, even *'an identical or similar occupation can be considered "relevant work experience"'*  (Felix,  in:  BeckOK,  TV-L,  §16 Rn.67). In addition, *"..it depends (is conditional?) on, that the previous occupation's knowledge, skillsets, professional expertise and experience required in the previous occupation are required or applicable to the employment in question"* (Felix, in: BeckOK, TV-L, §16 Rn.67).

To examine whether there is any work-related experience, the duties and conditions of the position to be filled must be specified, and compared with those of the previous occupation.  *"If at least half the periof of the previous job statisfy the specifications of the position, then work-related experience is considered to exist"* (Felix, in:BeckOK,  TV-L,  §16  Rn.68). In this calculation, periods of time as student or scientific assistant (wissenschaftliche Hilfskraft) are not considered relevant work-experience  (Felix, in: BeckOK, TV-L, §16 Rn.76).

### b.Staffing requirements and supplementary periods (förderliche Zeiten^[I'm unable to find a proper translation for this term. Essentially all periods that broadly correspond to periods where work similar to the position to be filled have been performed. These are  also periods of work not done under a collective agreement type contract (TV-L/TVÖD/etc.)]) (§16Abs.2 S.4TV-L)

In case of difficulties with filling a position, there may be strong  necessity^[original:*besondere Gewinnungsinteresse*] to fill the staffing requirements, or to hire employees for the long-term. In such cases, a higher experience-level can be assigned when '..no or few qualified candidates can be found without a higher Stufe assignment' (Spelge, ZTR 2011, 338, 345). This is an action that is not within the collective-agreement per se, and there is thus a discretionary decision. 

Supplementary periods (förderliche Zeiten) are those durations of work that are not technically relevant work-experience, but complement the requirements of position for other reasons. These include side-employments at private concerns or as freelancing. A PhD with a stipend could also be considered a free-lancing type supplementary work period. The recognition of supplementary periods follows according to the definition of § 16 Abs. 2 S. 4 TV-L, only when there is a strong necessity to fill staffing requirements. In general however, it is expected that when considering previous work-history, the staffing requirement clause is less likely to be used than the relevant work-experience clause. 

###. Full stipends without side-employment:
Even though a PhD title may be a requirement for a job position, stipend-financed PhD work is generally not included as relevant work-experience, especially by universities - which do not recognise its validity. For instance, it is argued that there is no 'real' employment in play (based on the BAG decision of 21.11.2013, BeckRS 2014, 65838) - which is the basis of consdering the existence of relevant work experience. The recognition of stipends as stipends as relevant experience is also not legally charted (Müller, in: BeckOK, TV-L, § 40 Nr. 5 zu § 16, Rn. 5). In practise however, it depends on the actual execution of the legal framework in place^[..alternative trans.?: In practise, it depends on the intent behind the legal framework]. It can therefore be argued that stipends parallel 'real' taxable employment, and must therefore be treated as such. The primary character of an employment is not that it provides social services, but that an outcome-based work must be executed, that need not necessarily result in success^[original: *'..sondern dass eine leistungsbezogene Arbeit ausgefuehrt wird, die nicht zwangsläufig
in einem Erfolg münden muss.'*]. A stipend is awarded based on a pre-defined purpose and time-period, which means without output there is no payment of the stipend, similar to 'real' employment contexts. 

Stipend-financed doctoral work is recognised as supplementary work experience only when there are additional services provided in the form of research of teaching related activities, on top of the primary doctoral work. Here too, a side-employment with the doctoral work is very helpful. 'Doctoral-stipends can be recognised only when in addition to the doctoral work, additional research contributions or teaching was performed' (Guidelines for the recognition of supplementary work experience of Berlin universities^[Leitfaden der Berliner Hochschulen zur Anerkennung förderlicher Zeiten, available online at https://www.abt2-t.tu-berlin.de/fileadmin/ref30/Themen_A-Z/Einstellung/Antraege/Leitfaden_foerderliche_Zeiten_P16_Abs2_TV-L.pdf).]).  Here too, it may be helpful  to get documented proof from the faculty or supervising professor to confirm the additional services and to request their consideration as relevant work-experience. In addition, the request may also include a request to consider staffing requirements, that highlight the lack of suitable candidates, whose experience is required for a succesful hire. 

### Full-stipends with additional employment 
The justification of a higher Stufe is easier when there is evidence for employment as a scientific assitant or employee (wissenschaftliche Mitarbeiter). The employment can be treated as additional services provided on top of the doctoral work. The time dedicated to these previous employments (part-time/full-time) is not as important. Sometimes^[not sure about this sentence's translation], part-time employment below 50% full-time is not considered, however, in general this is not the case in practise (Müller, in: Beck-OK, TVL, § 40). The exclusion of part-time employment as work-experience has been declared by the highest court of law - which ruled against a fixed minimum of part-time employment defined by the number of work-hours per week: 'A lower threshold for the validation of previous employment is not in line with highest-ranking law^[hoeheraengigem Recht]'(Müller, in: Beck-OK, TVL, § 40 Nr. 5 zu § 16 Rn. 4, BAG 27.3.2014 – BAG Aktenzeichen 6AZR57112 6 AZR 571/12 BeckRS 2014, 69697). If the work-hours/week is not considered sufficient  for inclusion as work experience, the legal statement above can be quoted and the decision argued against. <<<<Sentence not translated^[original: Denn die Voraussetzungen für eine
ergänzende einschränkende Auslegung der § 40 Nr. 5 TV-L sowie § 16 Abs. 2 S. 3
TV-L sind nicht erfüllt.]>>>>

The legal sitution for the consideration of scientific assistant positions held before the doctoral period is less clear. Work periods as student assistants (studentische Hilfskraftstellen) cannot be considered as they are not part of a employment-qualifying degree. This exclusion also applies for any employment as a scientific assistant, eg. occuring in the bridge period between student to doctoral phases. Despite this lack of recognition, the Tarifgemeinschaft deutscher Länder (TdL, rough transl. *Collective group/union of german states*) has also not supported the inclusion of student assistant positions as work experience. In case of ambiguity however, it may still help to use the arguments from the above sections to support one's case. 

### Other stipends/ Research stipends 
It is relatively easier to get a research stipend recognised as relevant work-experience, as these are typically associated tightly to specific research institutions. In the guidelines of the Berlin Universities it says 'Research stipends from inter/national endowments^[orig: 'Zuwendern'] will be recognised'.

There is also a 'postive  list' of stipends that are generallly recognised by Berlin universities. In case the stipend is not acknowledgement, an application for the stipend period as supplementary work experience can still be made. Here too, letters of support from the faculty or employer could be helpful. Referring to the way Berlin universities handle stipends in their published guideleines, along with a request for clarification of why the particular Stipend in question is not recognised can also be helpful. The list of stipends recognised as supplementary work-experience in the Berlin universities guidelines is: 

* DAAD post-doc international fellowship 
* EU-Marie-Curie-Stipendium
* DFG research stipend
* BMBF Bernstein Centrum
* Alexander von Humboldt research stipend
* Doctoral stipends of the DFG on acceptance to a graduate college
* Phase II doctoral stipends of the  Berlin Mathematical School – BMS
common graduate school of the mathematical-disciplines of the 3 Berlin
univerisities)
* Doctoral stipends of the Berlin International Graduate School of Natural Sciences and Engeneering (BIG-NSE) in the Excellence-Cluster UniCat programme

### General hints for proceeding
Over the course of the employment procedure, it is advisable to submit the employment periods (as scientific employee/assistant, teaching duties or employment in non-university institutions) with exact dates in advance and request these for consideration, before the experience-levels are assigned (Einstufung). It may also be strategic to submit the application for consideration of work experience after accepting the employment, so that one is not turned away on grounds of the higher salary demand. The application may be submitted in free-form, when there is no specific form specified. 

### 3. Case-histories 
A decisive factor for a stipend-holder turned out to be the presentation of a certificate/letter (Bescheinigung) from the stipend-awarding institution, so that the doctoral period could be considered relevant work-experience. With this move, the stipend-holder moved into Stufe 3, ie. an inclusion of 2 years work experience. Before this move, she  had only presented the award letters of the stipend, which were rejected on grounds tht the award letters do not necessary prove that the stipend was succesfully paid continuously till the end of the stated period. A separate letter/certificate from the stipend-awarding organisation clarified this matter. 

## 4. Concluding information and procedural suggestions 
The legal ambiguity and large room for interpretation in the recognition of  stipends as work experience in the context of the TV-L agreements ultimately depends on the goodwill of individual Universities. Therefore, it is of great importance for us stipend-holders to share the knowledge and information gained through experience. If you have any direct experience in this matter, or have any relevant tips, please share this with your representatives of the Promovierende Initiative, so that this guideline can be progressively bettered, especially the case-history section. 